"use client";
import { useEffect, useRef, useState } from "react";
import { createClient } from "@/lib/supabase/client";
type Message = { id: string; sender_type: "patient" | "ai" | "doctor" | "staff" | "system"; content: string; created_at: string };

export function PatientChat({ conversationId, initialMessages, initialMode }: { conversationId: string; initialMessages: Message[]; initialMode: "ai" | "waiting_doctor" | "doctor" }) {
  const [messages, setMessages] = useState(initialMessages); const [mode, setMode] = useState(initialMode); const [text, setText] = useState(""); const [state, setState] = useState<"idle"|"sending"|"responding"|"error">("idle"); const bottom = useRef<HTMLDivElement>(null);
  useEffect(() => { bottom.current?.scrollIntoView({ behavior: "smooth" }); }, [messages]);
  useEffect(() => { const supabase=createClient(); const timer=window.setInterval(async()=>{ const [{data},{data:current}]=await Promise.all([supabase.from("messages").select("id, sender_type, content, created_at").eq("conversation_id",conversationId).order("created_at"),supabase.from("conversations").select("mode").eq("id",conversationId).single()]); if(data)setMessages(data); if(current)setMode(current.mode); },8000); return()=>window.clearInterval(timer); },[conversationId]);
  async function send(){ const content=text.trim(); if(!content||(state!=="idle"&&state!=="error"))return; const clientMessageId=crypto.randomUUID(); setText(""); setState("sending"); setMessages(c=>[...c,{id:clientMessageId,sender_type:"patient",content,created_at:new Date().toISOString()}]); try{ const response=await fetch("/api/patient/chat",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({conversationId,content,clientMessageId})}); if(!response.ok)throw new Error(await response.text()); if(response.status===204||!response.body){setState("idle");return;} const sender=response.headers.get("x-apollomd-sender")==="system"?"system":"ai"; if(sender==="system")setMode("waiting_doctor"); setState("responding"); const responseId=`response-${clientMessageId}`; setMessages(c=>[...c,{id:responseId,sender_type:sender,content:"",created_at:new Date().toISOString()}]); const reader=response.body.getReader(),decoder=new TextDecoder(); while(true){const{done,value}=await reader.read();if(done)break;const chunk=decoder.decode(value,{stream:true});setMessages(c=>c.map(m=>m.id===responseId?{...m,content:m.content+chunk}:m));}setState("idle"); }catch{setState("error");}}
  const label=(sender:Message["sender_type"])=>sender==="patient"?"Você":sender==="ai"?"APolloMD":sender==="doctor"?"Equipe médica":"APolloMD";
  return <><div className="chat-messages">{messages.length?messages.map(message=><article className={`chat-message ${message.sender_type}`} key={message.id}><span>{label(message.sender_type)}</span><p>{message.content||"…"}</p><time>{new Intl.DateTimeFormat("pt-BR",{hour:"2-digit",minute:"2-digit",timeZone:"America/Sao_Paulo"}).format(new Date(message.created_at))}</time></article>):<div className="chat-welcome"><span>A</span><h2>Como você está hoje?</h2><p>Conte como está se sentindo ou tire uma dúvida sobre seu acompanhamento.</p></div>}<div ref={bottom}/></div><footer className="chat-composer">{mode!=="ai"?<div className="human-care-note">Sua conversa está sendo acompanhada pela equipe.</div>:null}{state==="error"?<div className="patient-error">Não foi possível concluir. Sua mensagem foi salva; você pode tentar novamente.</div>:null}<div><textarea value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void send();}}} maxLength={2000} rows={1} placeholder={state==="responding"?"APolloMD está respondendo…":"Escreva uma mensagem"} disabled={state!=="idle"&&state!=="error"}/><button onClick={()=>void send()} disabled={!text.trim()||(state!=="idle"&&state!=="error")} aria-label="Enviar">↑</button></div><small>Canal de acompanhamento. Em situações urgentes, procure atendimento adequado e não dependa exclusivamente deste chat.</small></footer></>;
}
