"use client";
import { useEffect, useLayoutEffect, useRef, useState } from "react";
import { createClient } from "@/lib/supabase/client";
type Message = { id: string; sender_type: "patient" | "ai" | "doctor" | "staff" | "system"; content: string; created_at: string };
type ActiveQuestion = { automation_step_id:string|null;response_type:string|null;response_options:string[]|null;response_required:boolean;response_min:number|null;response_max:number|null;response_unit:string|null } | null;

export function PatientChat({ conversationId, initialMessages, initialMode, initialQuestion, initialRedFlagConfirmation }: { conversationId: string; initialMessages: Message[]; initialMode: "ai" | "waiting_doctor" | "doctor"; initialQuestion:ActiveQuestion; initialRedFlagConfirmation:boolean }) {
  const [messages, setMessages] = useState(initialMessages); const [mode, setMode] = useState(initialMode); const [question,setQuestion]=useState(initialQuestion); const [redFlagConfirmation,setRedFlagConfirmation]=useState(initialRedFlagConfirmation); const [text, setText] = useState(""); const [state, setState] = useState<"idle"|"sending"|"responding"|"error">("idle"); const [showJump,setShowJump]=useState(false); const scroller=useRef<HTMLDivElement>(null); const followLatest=useRef(true); const initialized=useRef(false);
  function scrollToLatest(behavior:ScrollBehavior="smooth"){const element=scroller.current;if(!element)return;followLatest.current=true;setShowJump(false);element.scrollTo({top:element.scrollHeight,behavior});}
  function handleScroll(){const element=scroller.current;if(!element)return;const atBottom=element.scrollHeight-element.scrollTop-element.clientHeight<96;followLatest.current=atBottom;setShowJump(!atBottom);}
  useLayoutEffect(() => { if(!initialized.current){initialized.current=true;scrollToLatest("auto");return;}if(followLatest.current)scrollToLatest(state==="responding"?"auto":"smooth"); }, [messages,state]);
  useEffect(() => { const supabase=createClient(); const timer=window.setInterval(async()=>{ const [{data},{data:current},{data:pending}]=await Promise.all([supabase.from("messages").select("id, sender_type, content, created_at").eq("conversation_id",conversationId).order("created_at"),supabase.from("conversations").select("mode").eq("id",conversationId).single(),supabase.from("red_flag_confirmations").select("id").eq("conversation_id",conversationId).eq("status","pending").maybeSingle()]); if(data)setMessages(data); if(current)setMode(current.mode);setRedFlagConfirmation(Boolean(pending)); },8000); return()=>window.clearInterval(timer); },[conversationId]);
  async function send(value?:string){ const content=(value??text).trim(); if(!content||(state!=="idle"&&state!=="error"))return; followLatest.current=true;setShowJump(false);const clientMessageId=crypto.randomUUID(); setText(""); setState("sending"); setMessages(c=>[...c,{id:clientMessageId,sender_type:"patient",content,created_at:new Date().toISOString()}]); try{ const response=await fetch("/api/patient/chat",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({conversationId,content,clientMessageId})}); if(!response.ok)throw new Error(await response.text()); if(response.headers.get("x-apollomd-question")==="answered")setQuestion(null); const confirmation=response.headers.get("x-apollomd-red-flag-confirmation");if(confirmation==="pending")setRedFlagConfirmation(true);if(confirmation==="resolved")setRedFlagConfirmation(false); if(response.status===204||!response.body){setState("idle");return;} const sender=response.headers.get("x-apollomd-sender")==="system"?"system":"ai"; if(response.headers.get("x-apollomd-mode")==="waiting_doctor")setMode("waiting_doctor"); setState("responding"); const responseId=`response-${clientMessageId}`; setMessages(c=>[...c,{id:responseId,sender_type:sender,content:"",created_at:new Date().toISOString()}]); const reader=response.body.getReader(),decoder=new TextDecoder(); while(true){const{done,value}=await reader.read();if(done)break;const chunk=decoder.decode(value,{stream:true});setMessages(c=>c.map(m=>m.id===responseId?{...m,content:m.content+chunk}:m));}setState("idle"); }catch{setState("error");}}
  const label=(sender:Message["sender_type"])=>sender==="patient"?"Você":sender==="ai"?"ApolloMD":sender==="doctor"?"Equipe médica":"ApolloMD";
  const choices=redFlagConfirmation?["Sim","Não"]:question?.response_type==="single_choice"?question.response_options:question?.response_type==="boolean"?["Sim","Não"]:null;
  return <><div className="chat-scroll-region"><div className="chat-messages" ref={scroller} onScroll={handleScroll} aria-live="polite">{messages.length?messages.map(message=><article className={`chat-message ${message.sender_type}`} key={message.id}><div className="chat-message-avatar" aria-hidden="true">{message.sender_type==="patient"?"V":"A"}</div><div className="chat-message-body"><header><strong>{label(message.sender_type)}</strong><time>{new Intl.DateTimeFormat("pt-BR",{hour:"2-digit",minute:"2-digit",timeZone:"America/Sao_Paulo"}).format(new Date(message.created_at))}</time></header><p>{message.content||"…"}</p></div></article>):<div className="chat-welcome"><span>A</span><h2>Como você está hoje?</h2><p>Conte como está se sentindo ou tire uma dúvida sobre seu acompanhamento.</p></div>}</div>{showJump?<button className="chat-jump-latest" onClick={()=>scrollToLatest()} aria-label="Ir para as mensagens mais recentes">↓ Mensagens recentes</button>:null}</div><footer className="chat-composer">{mode!=="ai"?<div className="human-care-note">Sua conversa está sendo acompanhada pela equipe.</div>:null}{choices&&mode==="ai"?<div className="question-options">{choices.map(choice=><button key={choice} onClick={()=>void send(choice)} disabled={state!=="idle"&&state!=="error"}>{choice}</button>)}{question&&!question.response_required?<button onClick={()=>void send("Prefiro não responder")}>Prefiro não responder</button>:null}</div>:null}{question?.response_type==="number"?<small>Informe um número{question.response_min!=null?` a partir de ${question.response_min}`:""}{question.response_max!=null?` até ${question.response_max}`:""}{question.response_unit?` ${question.response_unit}`:""}.</small>:null}{state==="error"?<div className="patient-error" role="alert">Não foi possível concluir. Sua mensagem foi salva; você pode tentar novamente.</div>:null}<div><textarea value={text} onChange={e=>{setText(e.target.value);e.target.style.height="auto";e.target.style.height=`${Math.min(e.target.scrollHeight,128)}px`;}} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();void send();}}} maxLength={2000} rows={1} aria-label="Mensagem" placeholder={state==="responding"?"ApolloMD está respondendo…":"Mensagem para o ApolloMD"} disabled={state!=="idle"&&state!=="error"}/><button onClick={()=>void send()} disabled={!text.trim()||(state!=="idle"&&state!=="error")} aria-label="Enviar mensagem">↑</button></div><small>{state==="responding"?"ApolloMD está respondendo…":"O ApolloMD pode cometer erros. Em situações urgentes, procure atendimento adequado."}</small></footer></>;
}
