"use client";
import Link from "next/link";
import { useState } from "react";
import { patientLogout } from "@/app/patient/login/actions";
import { Breadcrumbs } from "@/components/breadcrumbs";

export function PatientShell({ children, patientName, currentTitle, currentSubtitle, conversations }: { children: React.ReactNode; patientName: string; currentTitle?: string; currentSubtitle?: string; conversations: { href: string; title: string; subtitle: string; active?: boolean }[] }) {
  const [open, setOpen] = useState(false); const [collapsed, setCollapsed] = useState(false);
  return <div className={`patient-app-shell ${collapsed ? "collapsed" : ""}`}><button className={`patient-drawer-scrim ${open ? "open" : ""}`} aria-label="Fechar menu" onClick={() => setOpen(false)} /><aside className={`patient-sidebar ${open ? "open" : ""}`}><div className="patient-sidebar-top"><Link className="patient-logo" href="/patient" onClick={() => setOpen(false)}><b>A</b><span>APolloMD</span></Link><button className="patient-collapse" onClick={() => setCollapsed((value) => !value)} aria-label={collapsed ? "Expandir barra lateral" : "Recolher barra lateral"}>⇤</button><button className="patient-drawer-close" onClick={() => setOpen(false)} aria-label="Fechar menu">×</button></div><nav aria-label="Acompanhamentos"><p>Acompanhamentos</p>{conversations.map((item) => <Link className={item.active ? "active" : ""} href={item.href} key={item.href} onClick={() => setOpen(false)}><span>◌</span><div><strong>{item.title}</strong><small>{item.subtitle}</small></div></Link>)}</nav><div className="patient-user"><span>{patientName.slice(0, 2).toUpperCase()}</span><div><strong>{patientName}</strong><small>Paciente</small></div><form action={patientLogout}><button aria-label="Sair">↗</button></form></div></aside><section className="patient-workspace"><header className="patient-topbar"><button onClick={() => setOpen(true)} aria-label="Abrir menu">☰</button><div><strong>{currentTitle || "APolloMD"}</strong>{currentSubtitle ? <span>{currentSubtitle}</span> : null}</div><span className="secure-indicator">Seguro</span></header><Breadcrumbs currentLabel={currentTitle} className="patient-breadcrumbs" />{children}</section></div>;
}
