import { PageHeader } from "@/components/admin/page-header";
import { FormDrawer } from "@/components/admin/form-drawer";
import { SettingsNav } from "@/components/admin/settings-nav";
import { getAdminContext } from "@/lib/auth/context";
import { createClient } from "@/lib/supabase/server";
import { saveRedFlagRule, toggleRedFlagRule } from "./actions";

export default async function RedFlagsSettings({ searchParams }: { searchParams: Promise<{ saved?: string; error?: string }> }) {
  const params = await searchParams; const context = await getAdminContext(); const db = await createClient();
  const { data: rules } = context.organization ? await db.from("red_flag_rules").select("id,name,description,severity,status,configuration").eq("organization_id", context.organization.id).order("created_at", { ascending: false }) : { data: [] };
  return <main className="admin-content"><PageHeader eyebrow="SISTEMA" title="RED Flags" description="Regras explícitas de atenção definidas pela equipe." /><div className="settings-layout"><SettingsNav active="RED Flags" /><section className="settings-content">{params.saved ? <p className="success-message">Regra salva.</p> : null}{params.error ? <p className="form-error">Não foi possível salvar a regra.</p> : null}<article className="panel rules-list">{rules?.length ? rules.map((rule) => { const configuration = rule.configuration as { pattern?: string }; return <section key={rule.id}><div><div><strong>{rule.name}</strong><small>{configuration.pattern} · {rule.severity} · {rule.status}</small></div><details className="row-menu"><summary aria-label={`Ações de ${rule.name}`}>⋮</summary><div><details><summary>Editar</summary><RuleForm rule={{ ...rule, pattern: configuration.pattern || "" }} /></details><form action={toggleRedFlagRule}><input type="hidden" name="id" value={rule.id} /><input type="hidden" name="status" value={rule.status} /><button className="text-button">{rule.status === "active" ? "Inativar" : "Ativar"}</button></form></div></details></div></section>; }) : <p className="muted-copy">Nenhuma regra configurada. Crie uma regra somente quando houver um termo operacional explícito.</p>}</article></section></div><FormDrawer label="Nova regra" title="Nova RED Flag" description="Defina o termo e a severidade operacional."><RuleForm /></FormDrawer></main>;
}
function RuleForm({ rule }: { rule?: { id: string; name: string; description: string | null; severity: string; pattern: string } }) { return <form action={saveRedFlagRule} className="drawer-form"><input type="hidden" name="id" value={rule?.id || ""} /><label>Nome<input name="name" defaultValue={rule?.name} required /></label><label>Termo ou expressão<input name="pattern" defaultValue={rule?.pattern} required /></label><label>Descrição<input name="description" defaultValue={rule?.description || ""} /></label><label>Severidade<select name="severity" defaultValue={rule?.severity || "medium"}><option value="low">Baixa</option><option value="medium">Média</option><option value="high">Alta</option><option value="critical">Crítica</option></select></label><button>Salvar regra</button></form>; }
