import { notFound } from "next/navigation";
import { PageHeader } from "@/components/admin/page-header";
import { getAdminContext } from "@/lib/auth/context";
import { createClient } from "@/lib/supabase/server";
import { duplicateFlow, saveStep, toggleStep, updateFlow } from "../actions";

type Step = { id:string;position:number;name:string;anchor:"episode_started_at"|"procedure_date"|"previous_step_completed_at";delay_value:number;delay_unit:"minutes"|"hours"|"days"|"weeks";message_content:string;is_active:boolean;step_type:"message"|"question"|"condition";response_type:"text"|"single_choice"|"number"|"boolean"|null;response_options:string[]|null;response_required:boolean;response_min:number|null;response_max:number|null;response_unit:string|null;response_timeout_value:number|null;response_timeout_unit:"minutes"|"hours"|"days"|"weeks"|null;timeout_strategy:"continue"|"stop";condition_question_step_id:string|null;condition_operator:string|null;condition_value:string|null;if_true_step_id:string|null;if_false_step_id:string|null };

export default async function FlowPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{saved?:string;error?:string}>}) {
  const {id}=await params,q=await searchParams,c=await getAdminContext(); if(!c.organization)notFound();
  const s=await createClient(),{data:flow}=await s.from("automation_flows").select("id,name,description,status,version,updated_at").eq("id",id).eq("organization_id",c.organization.id).maybeSingle(); if(!flow)notFound();
  const [{data:steps},{count:uses}]=await Promise.all([s.from("automation_steps").select("id,position,name,anchor,delay_value,delay_unit,message_content,is_active,step_type,response_type,response_options,response_required,response_min,response_max,response_unit,response_timeout_value,response_timeout_unit,timeout_strategy,condition_question_step_id,condition_operator,condition_value,if_true_step_id,if_false_step_id").eq("flow_id",id).order("position"),s.from("episode_automations").select("id",{count:"exact",head:true}).eq("flow_id",id)]);
  const all=(steps??[]) as Step[],editable=c.role==="organization_admin";
  return <main className="admin-content"><PageHeader eyebrow="AUTOMAÇÃO" title={flow.name} description={`Versão ${flow.version} · ${uses??0} acompanhamentos`}/>
    {q.saved?<p className="success-message">Alterações salvas para novas associações.</p>:null}{q.error?<p className="form-error">Não foi possível concluir. Verifique campos e referências do fluxo.</p>:null}
    {editable?<section className="panel automation-editor"><form action={updateFlow} className="patient-form"><input type="hidden" name="id" value={id}/><input name="name" defaultValue={flow.name} required/><input name="description" defaultValue={flow.description||""}/><select name="status" defaultValue={flow.status}><option value="draft">Rascunho</option><option value="active">Ativo</option><option value="inactive">Inativo</option></select><button>Salvar fluxo</button></form><form action={duplicateFlow}><input type="hidden" name="id" value={id}/><button className="text-button">Duplicar fluxo</button></form></section>:null}
    <section className="panel steps-panel"><h2>Etapas</h2>{all.map(step=><article key={step.id}><div><strong>{step.position}. {step.name} · {step.step_type}</strong><small>{step.anchor} + {step.delay_value} {step.delay_unit} · {step.is_active?"ativa":"inativa"}</small><p>{step.message_content}</p>{step.step_type==="question"?<small>Resposta: {step.response_type}{step.response_required?" · obrigatória":" · opcional"}</small>:null}{step.step_type==="condition"?<small>Condição: {step.condition_operator} {step.condition_value}</small>:null}</div>{editable?<details><summary>Editar</summary><StepForm flow={flow} step={step} steps={all}/><form action={toggleStep}><input type="hidden" name="flow_id" value={id}/><input type="hidden" name="step_id" value={step.id}/><input type="hidden" name="active" value={String(step.is_active)}/><button className="text-button">{step.is_active?"Inativar":"Ativar"}</button></form></details>:null}</article>)}{editable?<details className="create-disclosure"><summary>Adicionar etapa</summary><StepForm flow={flow} steps={all}/></details>:null}</section>
  </main>;
}

function StepForm({flow,step,steps}:{flow:{id:string;version:number};step?:Step;steps:Step[]}) {
  const prior=steps.filter(s=>s.step_type==="question"&&s.position<(step?.position??Number.MAX_SAFE_INTEGER)); const later=steps.filter(s=>s.position>(step?.position??0));
  return <form action={saveStep} className="step-form"><input type="hidden" name="flow_id" value={flow.id}/><input type="hidden" name="flow_version" value={flow.version}/><input type="hidden" name="step_id" value={step?.id||""}/>
    <input type="number" name="position" min="1" defaultValue={step?.position} placeholder="Posição"/><input name="name" defaultValue={step?.name} placeholder="Nome *" required/>
    <label>Tipo<select name="step_type" defaultValue={step?.step_type||"message"}><option value="message">Mensagem</option><option value="question">Pergunta</option><option value="condition">Condição</option></select></label>
    <label>Âncora<select name="anchor" defaultValue={step?.anchor||"procedure_date"}><option value="procedure_date">Data do procedimento</option><option value="episode_started_at">Início do episódio</option><option value="previous_step_completed_at">Conclusão da etapa anterior</option></select></label>
    <input type="number" name="delay_value" min="0" defaultValue={step?.delay_value??0} required/><select name="delay_unit" defaultValue={step?.delay_unit||"days"}><option value="minutes">Minutos</option><option value="hours">Horas</option><option value="days">Dias</option><option value="weeks">Semanas</option></select>
    <textarea name="message_content" defaultValue={step?.message_content} placeholder="Mensagem ou pergunta *" maxLength={2000} required/>
    <h3>Configuração da pergunta</h3><select name="response_type" defaultValue={step?.response_type||"text"}><option value="text">Texto</option><option value="single_choice">Escolha única</option><option value="number">Número</option><option value="boolean">Sim/Não</option></select><textarea name="response_options" defaultValue={step?.response_options?.join("\n")} placeholder="Uma opção por linha"/><select name="response_required" defaultValue={String(step?.response_required??true)}><option value="true">Obrigatória</option><option value="false">Opcional</option></select><input type="number" step="any" name="response_min" defaultValue={step?.response_min??""} placeholder="Mínimo"/><input type="number" step="any" name="response_max" defaultValue={step?.response_max??""} placeholder="Máximo"/><input name="response_unit" defaultValue={step?.response_unit||""} placeholder="Unidade"/>
    <input type="number" min="1" name="response_timeout_value" defaultValue={step?.response_timeout_value??""} placeholder="Timeout opcional"/><select name="response_timeout_unit" defaultValue={step?.response_timeout_unit||"hours"}><option value="minutes">Minutos</option><option value="hours">Horas</option><option value="days">Dias</option><option value="weeks">Semanas</option></select><select name="timeout_strategy" defaultValue={step?.timeout_strategy||"stop"}><option value="stop">Parar no timeout</option><option value="continue">Continuar no timeout</option></select>
    <h3>Configuração da condição</h3><select name="condition_question_step_id" defaultValue={step?.condition_question_step_id||""}><option value="">Pergunta anterior</option>{prior.map(s=><option key={s.id} value={s.id}>{s.position}. {s.name}</option>)}</select><select name="condition_operator" defaultValue={step?.condition_operator||"equals"}><option value="equals">igual</option><option value="not_equals">diferente</option><option value="greater_than">maior que</option><option value="greater_than_or_equal">maior ou igual</option><option value="less_than">menor que</option><option value="less_than_or_equal">menor ou igual</option></select><input name="condition_value" defaultValue={step?.condition_value||""} placeholder="Valor"/><select name="if_true_step_id" defaultValue={step?.if_true_step_id||""}><option value="">Se verdadeiro</option>{later.map(s=><option key={s.id} value={s.id}>{s.position}. {s.name}</option>)}</select><select name="if_false_step_id" defaultValue={step?.if_false_step_id||""}><option value="">Se falso</option>{later.map(s=><option key={s.id} value={s.id}>{s.position}. {s.name}</option>)}</select><button>Salvar etapa</button>
  </form>;
}
